apiVersion: v1
kind: Service
metadata:
    name: database-master
    labels:
        name: database-master
spec:
    selector: 
        name: database-master-replication-controller
    type: NodePort
    ports:
    - port: 3306
      nodePort: 32000
      name: mysql-master
    - port: 6379
      nodePort: 32001
      name: redis-master
