apiVersion: v1
kind: Pod
metadata:
    name: database-slave
    labels:
        name: database-slave
spec:
    containers:
    - name: mysql-slave
      image: mysql
      ports:
      - containerPort: 3306
    - name: redis-slave
      image: redis-slave
      ports:
      - containerPort: 6379
