apiVersion: v1
kind: ReplicationController
metadata:
    name: database-slave-replication-controller
    labels:
        name: database-slave-replication-controller
spec:
    replicas: 2
    selector:
        name: database-slave-replication-controller
    template:
        metadata:
            name: database-slave-replication-controller
            labels:
                name: database-slave-replication-controller
        spec:
            containers:
            #- name: mysql
            #  image: mysql
            #  ports:
            #  - containerPort: 3306
            #  env:
            #  - name: MYSQL_ROOT_PASSWORD
            #    value: root
            - name: redis-slave
              image: redis-slave
              ports:
              - containerPort: 6379
