apiVersion: v1
kind: Pod
metadata:
    name: database
    labels:
        name: database
spec:
    containers:
    - name: mysql
      image: mysql
      ports:
      - containerPort: 3306
    - name: redis
      imaga: redis
      ports:
      - containerPort: 6379
