apiVersion: v1
kind: ReplicationController
metadata:
    name: database-replication-controller
    labels:
        name: database-replication-controller
spec:
    replicas: 1
    selector: 
        name: database-replication-controller
    template:
        metadata:
            name: database-replication-controller
            labels:
                name: database-replication-controller
        spec:
            containers:
            - name: mysql
              image: mysql
              ports:
              - containerPort: 3306
              env:
              - name: MYSQL_ROOT_PASSWORD
                value: root
            - name: redis
              image: redis
              ports:
              - containerPort: 6379
