apiVersion: v1
kind: Service
metadata:
    name: database
    labels:
        name: database
spec:
    selector: 
        name: database-replication-controller
    type: NodePort
    ports:
    - port: 3306
      nodePort: 32000
      name: mysql
    - port: 6379
      nodePort: 32001
      name: redis
